scalar Upload
    @scalar(class: "Nuwave\\Lighthouse\\Schema\\Types\\Scalars\\Upload")

type User {
    id: ID!
    name: String!
    email: String!
    is_pro: Boolean!
    is_adm: Boolean!
    usage_limit: Int!
    events: [Event!]! @hasMany
    created_at: String!
    updated_at: String!
}

type Event {
    id: ID!
    public_id: String!
    name: String!
    date: String!
    time: String!
    capacity: Int!
    street: String!
    city: String!
    price: String
    description: String
    banner: String
    status: String!
    cover: String
    user: User! @belongsTo
    created_at: String!
    updated_at: String!

    subscribers_count: Int! @count(relation: "subscribers")
    is_subscribed: Boolean! @method(name: "getIsSubscribedAttribute")
}

type Query {
    me: User @guard(with: ["sanctum"]) @auth(guard: "sanctum")

    event(public_id: String! @eq): Event @find

    upcomingEvents(
        name: String
        city: String
        price: String
        date_filter: String
    ): [Event!]!
        @paginate(
            defaultCount: 6
            builder: "App\\GraphQL\\Queries\\UpcomingEventsQuery"
        )
}

extend type Query {
    mySubscribedEvents: [Event!]!
        @paginate(builder: "App\\GraphQL\\Queries\\MySubscribedEvents")
        @guard(with: ["sanctum"])
}

type Mutation {
    signup(name: String!, email: String!, password: String!): String!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\SignupMutation")

    login(email: String!, password: String!): String!
        @field(resolver: "App\\GraphQL\\Mutations\\Auth\\LoginMutation")

    createEvent(
        name: String!
        date: String!
        time: String!
        capacity: Int!
        street: String!
        city: String!
        price: String
        description: String
        banner: Upload
        cover: Upload
    ): Event!
        @field(resolver: "App\\GraphQL\\Mutations\\Event\\CreateEventMutation")
        @guard(with: ["sanctum"])

    updateEvent(
        id: ID!
        name: String
        date: String
        time: String
        capacity: Int
        street: String
        city: String
        price: String
        description: String
        banner: Upload
        cover: Upload
        status: String
    ): Event!
        @field(resolver: "App\\GraphQL\\Mutations\\Event\\UpdateEventMutation")
        @guard(with: ["sanctum"])

    deleteEvent(id: ID!): Boolean!
        @field(resolver: "App\\GraphQL\\Mutations\\Event\\DeleteEventMutation")
        @guard(with: ["sanctum"])

    subscribeToEvent(event_id: ID!): Boolean!
        @guard(with: ["sanctum"])
        @field(resolver: "App\\GraphQL\\Mutations\\Event\\SubscribeToEvent")
}
